name: Github CI
on: [push, pull_request]
jobs:
  build:
    name: Github CI - Branch
    runs-on: ubuntu-latest
    environment: github-ci
    steps:
      - name: Setup PHP 8.0
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          coverage: none
          extensions: mbstring, intl, pdo_sqlite, json, redis, grpc
          ini-values: apc.enabled=1, apc.shm_size=32M, apc.ttl=7200, apc.enable_cli=1, apc.serializer=php

      - name: Setup Memcached server
        uses: niden/actions-memcached@v7
      - name: Setup Redis server
        uses: zhulik/redis-action@v1.0.0
        with:
          redis version: '5'
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Setup GCP environment
        run: ./bin/ci/scripts/setup_gcp.sh

      - name: Install dependencies
        run: ./bin/ci/scripts/install_dependencies.sh

      - name: Run PHPCS
        run: ./vendor/bin/phpcs lib/  --report=summary

      - name: Run PHPMD
        run: ./vendor/bin/phpmd lib/ ansi phpmd.xml

      - name: Run PHPSTAN (lite)
        run: ./vendor/bin/phpstan analyse lib/ -l 2 -c phpstan_lite.neon 2>&1

      - name: Run TESTS
        run: php -f ./bin/ci/run_tests.php
